# Generated by Django 4.1.7 on 2023-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='iscomment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
