# Generated by Django 4.1.7 on 2023-07-07 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_notification_iscomment_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.commentpost'),
        ),
    ]
